const INCIDENT_FLOW=Object.freeze({NUEVA:['ASIGNADA','CERRADA'],ASIGNADA:['EN_PROCESO','NUEVA','CERRADA'],EN_PROCESO:['RESUELTA','ASIGNADA'],RESUELTA:['CERRADA','EN_PROCESO'],CERRADA:[]});
function incidentForClient_(inc){const result={};Object.keys(inc||{}).forEach(function(key){const value=inc[key];result[key]=value instanceof Date?formatDateTime_(value):value;});return result;}
function apiGetIncident(id){requireManager_();const inc=findIncident_(id);if(!inc)throw new Error('Incidencia no encontrada.');return{ok:true,incident:incidentForClient_(inc),history:getSheetRows_(APP.SHEETS.HISTORIAL).filter(r=>String(r.INCIDENCIA)===String(id)).map(r=>({...r,FECHA:formatDateTime_(r.FECHA)})),allowedNext:INCIDENT_FLOW[String(inc.ESTADO).toUpperCase()]||[]};}
function apiAssignIncident(id,responsable){const user=requireManager_();const target=String(responsable||'').trim().toLowerCase();if(!target)throw new Error('Indica un responsable.');if(!getAssignableManagers_().some(function(manager){return manager.email===target;}))throw new Error('El responsable debe ser un supervisor activo.');return updateIncidentWorkflow_(id,'ASIGNADA',{RESPONSABLE:target,FECHA_ASIGNACION:new Date()},user,'Asignación de responsable');}
function apiChangeIncidentState(id,newState,notes){const user=requireManager_(),state=String(newState||'').toUpperCase();if(state==='RESUELTA')throw new Error('Utiliza la acción Resolver e indica la solución aplicada.');return updateIncidentWorkflow_(id,state,{},user,notes||'Cambio de estado');}
function apiResolveIncident(id,solution){const user=requireManager_(),text=String(solution||'').trim();if(!text)throw new Error('Debes indicar la solución aplicada.');const result=updateIncidentWorkflow_(id,'RESUELTA',{SOLUCION:text,FECHA_RESOLUCION:new Date()},user,'Incidencia resuelta');const notification=sendIncidentResolvedNotificationSafely_(findIncident_(id));return Object.assign(result,{emailSent:notification.emailSent,emailWarning:notification.warning||''});}
function apiCloseIncident(id,notes){const user=requireManager_();return updateIncidentWorkflow_(id,'CERRADA',{},user,notes||'Incidencia cerrada');}
function findIncident_(id){return getSheetRows_(APP.SHEETS.INCIDENCIAS).find(r=>String(r.ID)===String(id))||null;}
function updateIncidentWorkflow_(id,nextState,extra,user,notes){const lock=LockService.getScriptLock();lock.waitLock(10000);try{const ss=getSpreadsheet_(),sh=ss.getSheetByName(APP.SHEETS.INCIDENCIAS),values=sh.getDataRange().getValues(),headers=values[0].map(String),idx=Object.fromEntries(headers.map((h,i)=>[h,i]));for(let r=1;r<values.length;r++){if(String(values[r][idx.ID])!==String(id))continue;const prev=String(values[r][idx.ESTADO]||'NUEVA').toUpperCase();const allowed=INCIDENT_FLOW[prev]||[];if(!allowed.includes(nextState))throw new Error(`Transición no permitida: ${prev} → ${nextState}`);values[r][idx.ESTADO]=nextState;Object.entries(extra||{}).forEach(([k,v])=>{if(idx[k]!==undefined)values[r][idx[k]]=v});sh.getRange(r+1,1,1,values[r].length).setValues([values[r]]);appendHistory_(id,'CAMBIO_ESTADO',prev,nextState,user.email,notes||'');return{ok:true,id:id,estado:nextState};}throw new Error('Incidencia no encontrada.');}finally{lock.releaseLock();}}
